version: "2"

services:
  gem:
    build: .
    working_dir: $PWD
    volumes:
      # in dev/test the nib binstub points to this path
      - .:/usr/src/app
      # for running integration specs
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      # for purposes of release
      - $HOME/.ssh:/root/.ssh
      - $HOME/.gitconfig:/root/.gitconfig
      - $HOME/.gem/credentials:/root/.gem/credentials
